CISM support for NorESM diagnostics
NordicESMhub/noresmdiagnostics pull request #16
Opened 2022-01-13 12:00 UTC by hgoelzer

This pull request adds basic CISM support to the NorESM diagnostics package. CISM diagnostic output can be selected as an additional component cism similar to the other components.

2022-02-14 22:45 UTC, YanchunHe requested changes
Some small revision of the code need to be done.

2022-02-14 22:45 UTC, YanchunHe commented on bin/diag_run
> +        elif [ "$model" == "cism" ] || [ "$model" == "cism" ]; then
change

```bash
elif [ "$model" == "cism" ] || [ "$model" == "cism" ]; then
```

to
```bash
elif [ "$model" == "cism" ]; then
```

??

2022-02-14 22:45 UTC, YanchunHe commented on bin/diag_run
> +                         echo "Valid options: cam, clm, cice, cism, all"
"Valid options: cam, blom/micom,clm, cice, cism, all"

2022-02-14 22:45 UTC, YanchunHe commented on packages/CAM_DIAG/amwg_template.csh
> +#!/bin/csh -e
Usually, we want to keep the scrip running even if there are errors.
So I would suggest to remove '-e' option.

2022-02-14 22:45 UTC, YanchunHe commented on packages/CAM_DIAG/amwg_template.csh
> +#    setenv PATH /usr/bin:/usr/local/bin:/usr/bin:/opt/ncl65/bin/:/opt/nco475/bin/:/opt/cdo197/bin
I see this is for debug only, so the comment can be removed.

2022-02-14 22:45 UTC, YanchunHe commented on packages/CAM_DIAG/amwg_template.csh
> +
clean up?

I don't there is problem with 'nco' path?

2022-02-17 11:40 UTC, hgoelzer commented
Hi Yanchun,
I have reverted the changes in amwg_template.csh and corrected the issues you marked in diag_run. I hope the pull request can go forward now. Thanks
    Heiko

2022-02-22 08:59 UTC, YanchunHe commented
Look good, I merge the changes. Thanks a lot, Heiko!

2022-02-22 09:00 UTC, merged